name: table_24
terrain:
  - { footprint: [4, 6, 14, 12] }
  - { footprint: [7, 17, 18, 40] }
  - { footprint: [19, 5, 25, 14] }
  - { footprint: [24, 17, 36, 27] }
  - { footprint: [24, 31, 32, 39] }
  - { footprint: [28, 5, 36, 13] }
  - { footprint: [35, 30, 41, 39] }
  - { footprint: [42, 4, 53, 27] }
  - { footprint: [46, 32, 56, 38] }
