name: table_19
terrain:
  - { footprint: [4, 17, 15, 27] }
  - { footprint: [5, 6, 15, 12] }
  - { footprint: [5, 31, 9, 37] }
  - { footprint: [15, 34, 19, 40] }
  - { footprint: [18, 11, 28, 16] }
  - { footprint: [18, 23, 28, 30] }
  - { footprint: [20, 34, 25, 36] }
  - { footprint: [25, 5, 28, 10] }
  - { footprint: [32, 14, 42, 21] }
  - { footprint: [32, 28, 42, 33] }
  - { footprint: [32, 34, 35, 39] }
  - { footprint: [35, 8, 40, 10] }
  - { footprint: [41, 4, 45, 10] }
  - { footprint: [45, 17, 56, 27] }
  - { footprint: [45, 32, 55, 38] }
  - { footprint: [51, 7, 55, 13] }
