"""Read-only view of battle state for renderers and reward calculators."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import numpy as np

from wargame_rl.wargame.envs.domain.entities import WargameModel, WargameObjective
from wargame_rl.wargame.envs.domain.fight import PairedFightResult
from wargame_rl.wargame.envs.domain.rules_quantities import RulesQuantities
from wargame_rl.wargame.envs.domain.shooting import PairedShootingResult
from wargame_rl.wargame.envs.domain.terrain import Terrain
from wargame_rl.wargame.envs.types.config import WargameEnvConfig
from wargame_rl.wargame.envs.types.game_timing import GameState
from wargame_rl.wargame.envs.types.geometry import Polygon


@runtime_checkable
class BattleView(Protocol):
    """Read-only interface to battle state.

    Implemented by WargameEnv (and later by Battle when used standalone).
    Allows renderers and reward calculators to depend on this protocol
    instead of the full Gymnasium environment.
    """

    @property
    def board_width(self) -> int: ...
    @property
    def board_height(self) -> int: ...
    @property
    def config(self) -> WargameEnvConfig: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def player_models(self) -> list[WargameModel]: ...
    @property
    def opponent_models(self) -> list[WargameModel]: ...
    @property
    def objectives(self) -> list[WargameObjective]: ...
    @property
    def deployment_zone(self) -> np.ndarray: ...
    @property
    def opponent_deployment_zone(self) -> np.ndarray: ...
    @property
    def deployment_outline(self) -> Polygon | None: ...
    @property
    def opponent_deployment_outline(self) -> Polygon | None: ...
    @property
    def current_turn(self) -> int: ...
    @property
    def last_reward(self) -> float | None: ...
    @property
    def last_player_shooting_results(self) -> list[PairedShootingResult]: ...
    @property
    def last_opponent_shooting_results(self) -> list[PairedShootingResult]: ...
    @property
    def last_player_fight_results(self) -> list[PairedFightResult]: ...
    @property
    def last_opponent_fight_results(self) -> list[PairedFightResult]: ...
    @property
    def last_reward_breakdown(self) -> dict[str, float]: ...
    @property
    def episode_reward(self) -> float: ...
    @property
    def game_clock_state(self) -> GameState: ...
    @property
    def n_rounds(self) -> int: ...
    @property
    def player_vp(self) -> int: ...
    @property
    def opponent_vp(self) -> int: ...
    @property
    def player_vp_delta(self) -> int: ...
    @property
    def terrain(self) -> Terrain: ...
    @property
    def player_max_ranges(self) -> np.ndarray: ...
    @property
    def opponent_max_ranges(self) -> np.ndarray: ...
    @property
    def player_advance_legality(self) -> np.ndarray: ...
    @property
    def player_charge_legality(self) -> np.ndarray: ...
    @property
    def player_declaration_legality(self) -> np.ndarray: ...

    @property
    def player_objective_target_legality(self) -> np.ndarray: ...
    @property
    def player_charge_target_legality(self) -> np.ndarray: ...
    @property
    def player_short_move_legality(self) -> np.ndarray: ...
    @property
    def rules_quantities(self) -> RulesQuantities: ...
    @property
    def opponent_vp_delta(self) -> int: ...

    def has_line_of_sight_between_points(
        self, x0: float, y0: float, x1: float, y1: float
    ) -> bool: ...

    def line_of_sight_matrix(
        self,
        origins: np.ndarray,
        targets: np.ndarray,
        candidates: np.ndarray | None = None,
    ) -> np.ndarray: ...
