name: Validate
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🚀 Install just
        uses: extractions/setup-just@v2

      - name: 🦾 Install dependencies
        run: just dev-sync

      - name: 💅 Format
        run: uv run ruff format --check

      - name: 🔍 Lint
        run: just lint

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🚀 Install just
        uses: extractions/setup-just@v2

      - name: 🦾 Install dependencies
        run: just dev-sync

      - name: 🧪 Test with coverage
        run: just test

      - name: 📊 Coverage PR comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml

  ci-passed:
    needs: [lint, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: |
          if [[ "${{ needs.lint.result }}" == "failure" ||
                "${{ needs.test.result }}" == "failure" ]]; then
            exit 1
          fi
